ALTER TABLE topics
    ADD COLUMN is_edited TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN edited_at INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE replies
    ADD COLUMN is_edited TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN edited_at INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE topics
    DROP COLUMN IF EXISTS edited_by;

ALTER TABLE replies
    DROP COLUMN IF EXISTS edited_by;
